apiVersion: v1
kind: Secret
metadata:
  name: pick-and-eat-api-secret
type: Opaque
stringData:
  DB_URL: {{ .Values.db.url | quote }}
  DB_USERNAME: {{ .Values.db.username | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  EXPIRATION_ACCESS_TOKEN: {{ .Values.jwt.expiration_access_token | quote }}
  REDIS_HOST: {{ .Values.cache.host | quote }}
  REDIS_PORT: {{ .Values.cache.port | quote }}