version: "3.9"

services:
    postgresql-db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: ${DB_PASSWORD}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
        volumes:
          - pgdata:/var/lib/postgresql/data 
        ports:
          - ${DOCKER_DB_PORTS}
    
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
        depends_on:
          - postgresql-db
        environment:
          ADMINER_DEFAULT_SERVER: postgresql-db
          ADMINER_DESIGN: dracula
    dragonfly:
      image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
      ulimits:
        memlock: -1
      ports:
        - "6379:6379"
      # For better performance, consider `host` mode instead `port` to avoid docker NAT.
      # `host` mode is NOT currently supported in Swarm Mode.
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
      # network_mode: "host"
      volumes:
        - dragonflydata:/data

volumes:
  pgdata:
  dragonflydata:
