# En mode dev uniquement, il ne faut pas exposer les credentials même encoder en base64
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: LePoissonSteve?
  POSTGRES_DB: pae-db