apiVersion: apps/v1
kind: Deployment
metadata:
  name: pick-and-eat-cache
  labels:
    app: pick-and-eat-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pick-and-eat-cache
  template:
    metadata:
      labels:
        app: pick-and-eat-cache
    spec:
      containers:
        - name: dragonfly
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
