apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  PROJECT_MODE: {{ .Values.project_mode | quote }}
  SERVER_PORT: {{ .Values.server.port | quote }}
  USE_TESTCONTAINERS: {{ .Values.tests.use_testcontainers | quote }}