apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
