# The CI pipeline to allow user to merge branch on develop.
name: CI for main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Detect next version from commits
        id: version
        run: |
          COMMITS=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s")
          if echo "$COMMITS" | grep -q "BREAKING CHANGE"; then
            echo "scope=major" >> $GITHUB_OUTPUT
          elif echo "$COMMITS" | grep -q "^feat"; then
            echo "scope=minor" >> $GITHUB_OUTPUT
          else
            echo "scope=patch" >> $GITHUB_OUTPUT
          fi
      - name: Run Axion Release and tag
        run: ./gradlew release -Prelease.scope=${{ steps.version.outputs.scope }} -Prelease.pushTagsOnly=true
        env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com

      - name: Get current version
        id: current
        run: |
            VERSION=$(./gradlew -q currentVersion)
            echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create release branch
        run: |
            git checkout -b release/v${{ steps.current.outputs.version }}
            git push origin release/v${{ steps.current.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.current.outputs.version }}
          name: Release v${{ steps.current.outputs.version }}
          generate_release_notes: true